services: docker

before_install:
  - docker -v

script:
  - make test_raid
  - python -m unittest  discover -p "test_raid.py" -v
  - make -C tests/e2e/ -j2 all
  - make -C tests/e2e/ test_1
  - make -C tests/e2e/ test_2

after_failure:
  - docker-compose -p "namespace1" -f tests/e2e/docker-compose.yml logs
  - docker-compose -p "namespace2" -f tests/e2e/docker-compose.yml logs
