services: docker

before_install:
  - docker -v
  - git clone https://github.com/bitdust-io/tests.git tests_e2e

  - mkdir -p tests_e2e/src/bitdust
  - rsync -rR . tests_e2e/src/bitdust
  - cd tests_e2e

install:
  - docker-compose up -d
script:
  - docker-compose exec test sh -c "pytest tests/ -v -s"
