version: 2.1
executors:
  my-custom-executor:
    docker:
      - image: cimg/python:3.8.12
      
jobs:
  bitdust-job:

    executor: my-custom-executor
    steps:
      - add_ssh_keys:
          fingerprints:
            - "63:39:d9:e7:7e:0e:d6:5f:3c:d9:c7:0e:11:ae:8b:db"
            - "a5:22:3f:fe:a2:66:38:e0:9b:c9:84:7f:2c:14:44:94"
            - "5e:4c:f9:93:14:d7:de:ae:d6:c6:6e:68:f9:4d:62:1c"
      - checkout
      - run: |
          ls -la /home/circleci/.ssh/
          cat /home/circleci/.ssh/config
          cat /home/circleci/.ssh/known_hosts
          git archive -o latest.zip HEAD
          ls -la ./latest.zip
          scp -o StrictHostKeyChecking=no ./latest.zip tester@p2p-alice.ai:.
          cat /home/circleci/.ssh/known_hosts
          echo "archived file latest.zip uploaded to the test machine"
          ssh -o StrictHostKeyChecking=no tester@p2p-alice.ai "rm -rf bitdust/; mkdir bitdust/; mv latest.zip bitdust/; cd bitdust/; unzip -o -q latest.zip; rm latest.zip; make test_unit; cd ..; rm -rf bitdust/"

workflows:
  my-custom-workflow:
    jobs:
      - bitdust-job
