version: 2
jobs:
  build:
    machine:
      image: circleci/classic:201808-01
    steps:
      - checkout
      - run:
          name: "Use Python v3.8.1"
          command: |
            pyenv versions
            pyenv global 3.8.1
      - run:
          name: "Build"
          command: |
            make test_unit
            make regress_prepare
            make regress_run
            make regress_report
